allow_file:
- cbz
- CBZ
- zip
- ZIP
allow_image:
- jpg
- JPG
- png
- PNG
setting:
  format: jpg
  jpg_optimize: '97'
  model_name: realesr-animevideov3
  replace_origin: true
  tile_size: 0 (Auto)
  tta_mode: false
  upscale_ratio: '2'
temp_dir: ./temp
