setting:
  format: jpg
  jpg_optimize: 100 (OFF)
  model_name: realesr-animevideov3
  tile_size: 0 (Auto)
  tta_mode: false
  upscale_ratio: '2'
allow_file:
  - cbz
  - CBZ
  - zip
  - ZIP
allow_image:
  - jpg
  - JPG
  - png
  - PNG
temp_dir: ./temp